#!/usr/bin/env python
import sys

from clint.textui import colored


green = lambda s: colored.green(s, bold=True, always=True)
red = lambda s: colored.red(s, bold=True, always=True)

# always=True not honored??
import os
os.environ['CLINT_FORCE_COLOR'] = '1'

for line in sys.stdin:
    if line.startswith('+'):
        line = green(line)
    elif line.startswith('-'):
        line = red(line)
    print(line.rstrip())
