#!/usr/bin/env python
import sys

from clint.textui import colored


green = lambda s: colored.green(s, bold=True)
red = lambda s: colored.red(s, bold=True)


for line in sys.stdin:
    if line.startswith('+'):
        line = green(line)
    elif line.startswith('-'):
        line = red(line)
    print(line.rstrip())
