#!/usr/bin/env python
from os.path import expanduser
from os import listdir
import subprocess
import os

# TODO: arrow keys
# UP = '\x1b[A'
# LEFT = '\x1b[D'
# RIGHT = '\x1b[C'
# DOWN = '\x1b[B'

LEFT = 'h'
DOWN = 'j'
UP = 'k'
RIGHT = 'l'

# https://github.com/mbadolato/iTerm2-Color-Schemes
ITERM2_COLOR_SCHEMES_DIR = expanduser('~/src/iTerm2-Color-Schemes')
SCHEMES_DIR = ITERM2_COLOR_SCHEMES_DIR + '/schemes'
SCHEMES = listdir(SCHEMES_DIR)
APPLY_SCRIPT = ITERM2_COLOR_SCHEMES_DIR + '/tools/preview.rb'


class Getch(object):
    """
    http://stackoverflow.com/questions/510357/python-read-a-single-character-from-the-user
    """
    def __init__(self):
        import tty, sys

    def __call__(self):
        import sys, tty, termios
        fd = sys.stdin.fileno()
        old_settings = termios.tcgetattr(fd)
        try:
            tty.setraw(sys.stdin.fileno())
            ch = sys.stdin.read(1)
        finally:
            termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
        return ch


getch = Getch()


def apply_color_scheme(scheme):
    subprocess.check_call([APPLY_SCRIPT, SCHEMES_DIR + '/' + scheme])

i = 0
while True:
    key = getch()
    if key in {LEFT, UP}:
        i -= 1
    elif key in {RIGHT, DOWN}:
        i += 1
    else:
        exit(0)
    scheme = SCHEMES[i]
    print i, scheme.split('.')[0]
    apply_color_scheme(scheme)
