COMPANIES: ID, NAME
PEOPLE: ID, NAME
JOBS: COMPANY_ID, PEOPLE_ID





WITH SHARED_PEOPLE AS (SELECT COMPANY_2.NAME AS COMPANY_NAME, COUNT(*) AS PEOPLE_IN_COMMON FROM JOBS AS JOBS_1
                       INNER JOIN JOBS AS JOBS_2 ON JOBS_1.PEOPLE_ID = JOBS_2.PEOPLE_ID
                       INNER JOIN COMPANIES AS COMPANY_1 ON COMPANY_1.id = JOBS_1.COMPANY_ID
                       INNER JOIN COMPANIES AS COMPANY_2 ON COMPANY_2.id = JOBS_2.COMPANY_ID
                       WHERE COMPANY_1.NAME = 'Ford' AND COMPANY_2.NAME != 'Ford'
                       ORDER BY COMPANY_2.NAME
                       GROUP BY COMPANY_2.NAME)
SELECT COMPANY_NAME, PEOPLE_IN_COMMON FROM SHARED_PEOPLE
ORDER BY PEOPLE_IN_COMMON, COMPANY_NAME;
