#!/usr/bin/env python
from sys import stdout


class REPL:

    def run(self):
        while True:
            string = input('> ')
            parse_tree = self.parse(string)
            output = self.eval(parse_tree)
            stdout.write(output + '\n')

    def parse(self, string):
        return Expression()

    def eval(self, parse_tree):
        return 'result'


class Expression:
    pass


if __name__ == '__main__':
    REPL().run()
